### ISSUE TITLE
Unable to run mtc_sample launch file

### ISSUE THREAD

**Issue by minku1219** [MarqRazz/MoveIt.BT#1]
Hi, I am working on your package for using it with our project.
I tried launching the mtc_samples launch file but was unable to load the bt plugins.
I am getting the following symbol error.
Could you please provide me with the fix or solution for that.
I am using ubuntu 22.04 and moveit_task_constructor stable release for humble from source.

I have also attached the error screenshot.

Error:-

[INFO] [launch]: All log files can be found below /home/tcs/.ros/log/2024-09-10-12-22-35-661935-tcs-Precision-7710-100741
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [sample_bt_executor-1]: process started with pid [100742]
[sample_bt_executor-1] /home/tcs/Workspace/projects/3rdparty/BehaviorTree.ROS2/install/btcpp_ros2_samples/lib/btcpp_ros2_samples/sample_bt_executor: symbol lookup error: /home/tcs/Workspace/projects/3rdparty/BehaviorTree.ROS2/install/btcpp_ros2_samples/lib/btcpp_ros2_samples/sample_bt_executor: undefined symbol: _ZN2BT10Blackboard14rootBlackboardEv
[ERROR] [sample_bt_executor-1]: process has died [pid 100742, exit code 127, cmd '/home/tcs/Workspace/projects/3rdparty/BehaviorTree.ROS2/install/btcpp_ros2_samples/lib/btcpp_ros2_samples/sample_bt_executor --ros-args --params-file /home/tcs/Workspace/projects/3rdparty/MoveIt.BT/install/mtc_samples/share/mtc_samples/config/sample_mtc_executor.yaml'].
![Screenshot from 2024-09-10 12-22-46](https://github.com/user-attachments/assets/f3518d54-714e-4c54-8552-33528d6519b8)

**Comment by MarqRazz** [comment]
Sorry this library is highly subject to change, includes limited support, and assumes you know how to setup a colcon workspace. You appear to have a non-standard workspace that is missing dependencies from source.

You should have the following folder structure and rosdep should return success when ran in the root of your workspace.
- `colcon_ws/src/MoveIt.BT`
- `colcon_ws/src/`all packages listed [here](https://github.com/MarqRazz/MoveIt.BT/blob/main/moveit_bt.repos) [you get these from running vcs import]

**Comment by minku1219** [comment]
Hi @MarqRazz , Thanks for the response.
